# Generated by Django 4.1.5 on 2023-02-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sensor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor'),
        ),
    ]
