# Generated by Django 4.1.5 on 2023-02-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor'),
        ),
    ]
