# Generated by Django 4.1.5 on 2023-02-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_measurement_picture_alter_measurement_sensor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='picture',
        ),
    ]
