# Generated by Django 4.1.5 on 2023-02-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_measurement_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
